### ISSUE TITLE
Improvement of package stability by fixing package versions

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/FuseTS#103]
### Description
It is quite common that the installations of packages tend to run into problems as time goes on, due to various updates of the dependencies of the package itself. 

### Recommendations
It might be beneficial to fix the versions of the package dependencies, to ensure that the library is always installable. Updates of the library or the dependencies can then be performed regularly and manually. It’s possible that there are better ways of ensuring the stability of a library, so it is possible that the suggestion proposed here might not be the optimal one.

**Comment by mlubej** [comment]
Covered by #84, closing.
