### ISSUE TITLE
Download NDVI for Larger Area finished but still running?

### ISSUE THREAD

**Issue by yakubhariana70** [Open-EO/FuseTS#126]
I want to calculate the phenology of my own AOI in Indonesia. Before that, I used the existing BiDS workshop Jupyter Notebook file and tried to modify and change the AOI to my location. I don't know, if is there any fault in my code or if the problem comes because of the larger area I define.

This is my jupyter notebook on G-Colab [Demak NDVI](https://colab.research.google.com/drive/1ri1XHyphFYqWTdFR4ANgK8Mh2BVSn6GW?usp=sharing)

Below is the screenshot of my endless running on VSCode
![image](https://github.com/Open-EO/FuseTS/assets/72399616/350db723-ac2a-4bde-b4d7-382036d48afb)

Looking forward to any solution I could try. Thank 🙏

**Comment by jdries** [comment]
Hi,
the easiest thing to try for this area is to use openeo.dataspace.copernicus.eu
It runs directly on the full archive of Sentinel-2 L2A data, so it's faster for areas like yours where the data is not cached in the Terrascope backend. You will have to create a new account, but it's free and you'll get more credits compared to Terrascope.

The load_collection call is also missing a 'max_cloud_cover' parameter, please set it to a sensible value, like 85. This should also speed things up.

Note that for questions on performance of openeo.vito.be, you can use forum.openeo.cloud. The Copernicus dataspace also has a dedicated forum.
