### ISSUE TITLE
Make an algorithm inventory

### ISSUE THREAD

**Issue by handeerdem** [Open-EO/FuseTS#43]
Inventory of within-consortium available TS processing and fusion algorithms and collection of public additional algorithms
- [ ] subtask A
- [ ] subtask B
- [ ] subtask C

**Comment by handeerdem** [comment]
- [ ] do x
- [ ] do y
- [ ] do z

**Comment by JanssenBrm** [comment]
@msalinero / @JochemV  - does it make sense to keep this open? I don't see it as part of a WP1 deliverable. The algorithm inventory, supported in FuseTS, should be part of the official docs of the library.

**Comment by msalinero** [comment]
The algorithm inventory is covered in the Technical Note, one of the deliverables of WP1. So I think we can safely close this issue.
