### ISSUE TITLE
Setup of continuous integration

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#44]
- Add setuptools files
- Github actions for building/testing/packaging
- Publish into artifactory for dev builds, pypi for prod?

**Comment by soxofaan** [comment]
created initial setuptool files
and uploaded v 0.0.1 (which contains nothing yet) to https://pypi.org/project/fusets/  to reserve the package name there

**Comment by soxofaan** [comment]
now also added github workflow for running lint check and tests

**Comment by soxofaan** [comment]
now also added Jenkinsfile to do dev snapshot builds
uploaded to https://artifactory.vgt.vito.be/api/pypi/python-openeo index:

```
$ pip search fusets --index https://artifactory.vgt.vito.be/api/pypi/python-openeo
fusets (0.0.1.dev20220413+main.7)  - Time Series Fusion toolbox integrated with openEO
```

**Comment by soxofaan** [comment]
I think it's best to close this ticket and leave the "publish to pypi for prod" part for a separate ticket later when things are more fleshed out
