### ISSUE TITLE
Setup of documentation/website

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#45]
Provide basic structure within the repo for documenting the library (e.g. using markdown/Sphinx)
If possible, use github actions to publish as github pages.

Website can also use static generator mechanism, to be investigated.

**Comment by soxofaan** [comment]
did a bit of research and Markdown can be used (alongside RST) in Sphinx.
MyST seems to be the [recommended "plugin" to do this nowadays

- https://myst-parser.readthedocs.io/en/latest/
- https://www.sphinx-doc.org/en/master/usage/markdown.html

**Comment by soxofaan** [comment]
I've set up
- basic doc structure
- automated building with github actions
- publishing to https://open-eo.github.io/FuseTS/

**Comment by soxofaan** [comment]
Did initial setup of autodoc, but that's pretty empty at this point (no real source code in the package, e.g see #46 )

**Comment by soxofaan** [comment]
I think we can close this issue for now, the main original points are covered
