### ISSUE TITLE
Refine src code tree

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#46]
Now functions are directly part of jupyter notebooks.

Create better (but simple) module structure, following python guidelines, with one or two algorithms that are now in notebooks.
Move notebooks to separate folder (don't have to be part of the eventual wheel).
Communicate to project colleagues, or write project guidelines.

Library also has to be usable without openEO!

**Comment by soxofaan** [comment]
- [ ] move (reusable) functions from notebook to real `fusets` packages/modules
- [ ] unit tests for these functions
- [ ] use these `fusets` packages in notebooks instead of defining them in the notebooks
- [ ] move notebooks out of `src/fusets`

**Comment by soxofaan** [comment]
Started with PR #49 to extract reusable functions from existing notebooks

**Comment by soxofaan** [comment]
Restructured src and notebook tree
