### ISSUE TITLE
Putting together the survey for the stakeholders and the wider community (DEL-01)

### ISSUE THREAD

**Issue by mlubej** [Open-EO/FuseTS#47]
It is time to put together some concrete survey which can be provided to the stakeholders. This survey will serve as a basis for sending it out to a wider community on LPS22 in May. This was decided in the Progress Meeting no. 1, meaning that the results of the survey for the wider community (and potentially the updated survey) can be sent to ESA later on as an addendum.

If I understand correctly, Google Forms are most widely used for such occasions, but I remember some survey-like functionality being available also in MS Teams? Can someone more knowledgeable about the topic please kindly share their experiences?

Based on the conversations with experienced project managers it was suggested to structure the survey in the following manner:
- a generic Earth Observation / Remote Sensing part
- a use case specific part (showcased use cases from the AI4FOOD project are used here)

Questions in the second part focus in depth on the use case specific aspects. Questions can be repeated across sections, if they touch common dilemmas, since (I imagine) some survey partakers might skip some sections entirely.

TODO:
- [x] the first objective is to discuss regarding the survey platform
- [x] the second objective is to gather generic and use-case specific questions
- [x] the third objective is to organize the questions and text into a proper survey

Feedback or suggestions are appreciated.

**Comment by JanssenBrm** [comment]
I believe this ticket can be closed as the first survey was delivered and presented at PDR. During CDR the decision was made to currently not focus on setting up a second survey.
