### ISSUE TITLE
publish package to pypi

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/FuseTS#48]
Under #44 I already set up the basic package files (setup.cfg, setup.py, Jenkinsfile, .github/workflows)  for CI and (dev snapshot) packaging.

Once the package is more ready for general usage, we should also publish "official" releases to pypi

**Comment by JanssenBrm** [comment]
This issue is currently causing #90

**Comment by JanssenBrm** [comment]
v2.0.0 has been published to PyPi. We've also added  a new page in the documentation with more detailed steps on how to execute a release.
