### ISSUE TITLE
Documentation: use rio-xarray to load Sentinel-2 JPEG 2000

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#59]
Write a sample that shows how to create a FuseTS compatible dataset from original Sentinel-2 products.

Ideas:
- use rio-xarray
- use stac catalog to retrieve file locations, e.g. on Terrascope?
- load data from http links to avoid depending on data download, maybe based on C-Scale data federation?

**Comment by JanssenBrm** [comment]
- [ ] Add sample code to the document showcasing on to load different bands from a SAFE-based directory into a single datacube

**Comment by GriffinBabe** [comment]
@JanssenBrm  I'm proposing to save a SAFE S2-L2A product in our artifactory, packed as zip. This way, all the users can try the sample code using the same data.

**Comment by JanssenBrm** [comment]
@jdries  - Can you verify if the PR is OK?
