### ISSUE TITLE
SRD-07 data retrieval from openEO: raw bands, by bbox

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#62]
Implement a utility method that retrieves bands from multiple platforms as a dataarray.

Inputs:
- time range
- bbox
- projection and resolution (optional)
- bands
- platforms (sentinel-1, sentinel-2), or openEO collection ID's

**Comment by mlubej** [comment]
Can you explain what exactly would be the benefit of such a utility method? It seems to me that working with openEO directly is quite straightforward and I would just like to understand what issue we are trying to solve

**Comment by jdries** [comment]
In fact, I finished this one already:
https://open-eo.github.io/FuseTS/api.html#fusets.openeo.load_cubes

The benefit is indeed really in the details, but it allows for instance to load a spec from json or dictionary and turn it into an openEO datacube:
```

    spec = {
        "collections": {
            "SENTINEL2_L2A": {"bands":["B02","B03","B04"],"mask_scl_dilation":{}},
            "SENTINEL1_GRD": {}
        },
        "spatial_extent": [5.039291,51.166858,5.243225,51.319455]
    }
    cube = load_cubes(**spec, openeo_connection=connection)
```
The equivalent openEO code would be a little bit longer, and style-wise more procedural rather than the 'declarative' approach taken here. There have been users that indicated having a preference for this. This could also be something that's rather something for the openEO Python client lib.
