### ISSUE TITLE
SRD-09 document temporal averaging

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#64]
Document how to achieve temporal averaging both in openEO and XArray.
Can be a FuseTS method if required code is substantial enough.

**Comment by JanssenBrm** [comment]
- [ ] Add a section to the documentation (https://open-eo.github.io/FuseTS/design.html#data-cubes) to show how temporal averaging can be done using both openEO and xarray.

An example within openEO:
https://github.com/Open-EO/openeo-community-examples/blob/main/python/BasicSentinelMerge/sentinel_merge.ipynb

**Comment by JanssenBrm** [comment]
@jdries  - Can you verify if the content is as expected?
