### ISSUE TITLE
SRD-15 Customizable peak/valley detection

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#65]

**Comment by mlubej** [comment]
Hi @jdries,

I'm trying to implement this function, but I'm having a bit of trouble identifying how to fit the output in the results. The function recognizes peak/valley patterns in the input array (according to some parameters). Does this mean that the output results should be a boolean time series appended to the cube, or something else?

**Comment by jdries** [comment]
Yes indeed, I believe you'll either have to map to boolean, or a number with some defined legend (e.g. nothing=0,peak=1,valley=2)

The return type can perhaps be a new xarray.DataArray

**Comment by mlubej** [comment]
Another thing - I noticed a lot of tests/examples using the malawi_sentinel2.nc from https://artifactory.vgt.vito.be/testdata-public, but unfortunately this dataset doesn't have `B08` for calculating NDVI. What do you propose to do in this case?

**Comment by mlubej** [comment]
I can also prepare a custom datacube, if it can be shared along with your other test data. It's about 5 MB in size.

**Comment by jdries** [comment]
Yes, we can put more data on artifactory if needed.
Where possible, I would also use synthetic data, some tests also do this.
For instance, for peak valley detection, the sinusoidal might already be a good one.

Jeroen Dries
TAP - Centre for Remote Sensing and Earth Observation Processes
VITO NV | Boeretang 200 | 2400 Mol
tel. +32 14 33 55 11 | ***@***.***<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=mailto%3avoornaam.naam%40vito.be>
***@***.******@***.******@***.******@***.***<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=https%3a%2f%2fwww.facebook.com%2fVITObelgium>
________________________________

**Comment by mlubej** [comment]
> For instance, for peak valley detection, the sinusoidal might already be a good one.

Sorry for not replying, in the end this is what I used, as you suggested. Merged in https://github.com/Open-EO/FuseTS/pull/69

Is there anything else left to be done before closing this ticket?

**Comment by jdries** [comment]
Great, closing!
