### ISSUE TITLE
SRD-16 pair-wise similarity score between two time series

### ISSUE THREAD

**Issue by jdries** [Open-EO/FuseTS#66]
FuseTS should allow computing a pair-wise similarity score between two time series.

**Comment by mlubej** [comment]
Discussed at the meeting yesterday that calculating similarity scores between two time series doesn't make much sense on the pixel level and as a datacube function. This is usually useful in the context of comparing e.g. NDVI time-series of two parcels, so we have to think about the fingerprint of the functions here.

Perhaps something along a function which accepts a list of timeseries (a 2D array where axis 0 represents different time series and axis=1 represents different timestamps), and a metric lambda function which accepts two time series returns a score. 

The output would be a 2D matrix of distance scores for each pair of the input timeseries

```python
def similarity_score(timeseries: np.ndarray, metric_function: Any) -> np.ndarray:
    """
    Algorithm for calculating similarity scores between input timeseries

    Args:
        timeseries: a list of timeseries to be compared (should have the same timestamps)
        metric: a function to be used to compare two time series

    Returns:
        a 2D matrix of distance scores for each pair of the input timeseries
    """
```

@jdries how does that sound?

**Comment by jdries** [comment]
I think the basis is fine, but can we use XArray data structures as well? Or a wrapper based on XArray?

**Comment by mlubej** [comment]
Can you explain what the internal structure of the XArray would be here?

so you need a time dimension, NDVI values for each timestamps, and then several entries of these time series. Does this then mean we need a coordinate which is like the index of the specific time series?

**Comment by mlubej** [comment]
I don't think this functionality makes sense for the pixel-level application to be run on open-eo/fuse-ts, it has more to do with the off-line processing of pixel-aggregated signals, where things become very much user specific, so I'll just close this.
