### ISSUE TITLE
Whittaker doesn't work properly for non-null values of the prediction_period parameter

### ISSUE THREAD

**Issue by mlubej** [Open-EO/FuseTS#85]
Testing out the tutorial for the FOSS4G I found out the following.

Smoothing the time series with Whittaker and predicting on the same dates works as expected (case with `prediction_period = None`)

![image](https://github.com/Open-EO/FuseTS/assets/37869250/926d086a-9577-4b80-a09f-223b7a435e73)

But in case of a custom provided `prediction_period = 'P5D'` parameter things seem to go sour:

![image](https://github.com/Open-EO/FuseTS/assets/37869250/738afd4d-b444-40fb-98b3-0f06e8a9fb61)

The issue seems to be that the output xarray in this case doesn't have the time coordinate set.

(cc. @JanssenBrm)

**Comment by msalinero** [comment]
Seems that the starting custom date is getting misplaced in epoch. And also the rest of the time series 
![image](https://github.com/Open-EO/FuseTS/assets/9076763/d99de0e4-2b0c-4421-a063-9fe05d3739f5)

Maybe @jdries can help, as he did the xarray wrapper around the core function.
