### ISSUE TITLE
Introduce black and potentially other formatters to the repository

### ISSUE THREAD

**Issue by mlubej** [Open-EO/FuseTS#87]
The library is a bit of a mess, with no proper code formatting, making it harder for people to contribute.

It would make sense to:
- update the library to some formatting standards
- add/update automatic formatting tests as github actions (tests should pass before merging)
  - however, the above requires a generally passing builds

**Comment by soxofaan** [comment]
Just FYI: we starter introducing the black code style in the openeo client library in a gradual way, through [darker](https://github.com/akaihola/darker) and [pre-commit](https://pre-commit.com/). 
It's documented at https://open-eo.github.io/openeo-python-client/development.html#pre-commit-for-basic-code-quality-checks  and the pre-commit config we currently use is at https://github.com/Open-EO/openeo-python-client/blob/master/.pre-commit-config.yaml

**Comment by zigaLuksic** [comment]
Is `black` preferred? Recently `ruff` added a formater which agrees with black in 99% of cases. It's rather inconsequential which one gets chosen, but i assume down the line import sorting would also be desired (which can be covered with ruff to also remove unneeded imports). And any kind of linting can also be done via ruff.

It's a bit less tools, but really not that different from having black + isort/ruff.
