### ISSUE TITLE
openEO is not returning all bands after UDF execution

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/FuseTS#92]
On the `openeo-publish` branch we are currently integrating the different FuseTS services into openEO. One of the services we are curently working on is the Phenology service. In the following file, you can find a function that tests the Phenology UDF through openEO:

https://github.com/Open-EO/FuseTS/blob/openeo_publish/src/fusets/openeo/services/publish_phenology.py#L34

When the UDF is executed, the result seems to be valid datacube that contains 18 bands (see log entry with `Phenology result` . Each of these bands represent one of the phenology metrics that are calculated.

<img width="982" alt="MicrosoftTeams-image" src="https://github.com/Open-EO/FuseTS/assets/10883374/51cc5af0-f22c-46c2-9ba0-abacb9c80c8c">

However, after downloading the result, there is only 1 band left. It looks like some of the band information gets lost.

![image](https://github.com/Open-EO/FuseTS/assets/10883374/15b2d994-2897-4c82-8ac3-8d40d4d3bfa2)

**Comment by JanssenBrm** [comment]
I'm wondering if this is caused by using the `apply_dimension` as the data variable of the downloaded netcdf looks pretty strange:
 ```
var        (phenology, y, x) float64 0.8873 0.8689 0.8909 ... 0.8858 0.9385
```

I've also tried the following paths, but without success:
* Using the `reduce_dimension`, but no improvements there, with or without the `t` dimension (on which I reduce the data cube).
* Manually updating the metadata of the datacube using the following code. This gives the same result.
```python
metadata = CollectionMetadata({})
metadata = metadata.add_dimension('var', '', 'bands')\
    .rename_labels(dimension='var', target=phenology_bands)
phenology.metadata = metadata
```
* Updating the dimensions using the openEO functions, as demonstrated below. Executing this will result in an error that a band called `bands` already exists. When removing the `add_dimension` statement, another error is thrown (`ValueError: Invalid dimension 'bands'. Should be one of ['t', 'x', 'y']` )
```python
phenology = phenology.add_dimension('bands', phenology_bands[0], 'bands')
phenology = phenology.rename_labels(dimension='bands', target=phenology_bands)
```

**Comment by JanssenBrm** [comment]
@soxofaan / @jdries  - FYI

**Comment by JanssenBrm** [comment]
I've also tried using the `apply_neighborhood` function with the following code:

```python
  size = 125
    phenology = base_ndvi.apply_neighborhood(process=lambda x: run_udf(x, udf=load_phenology_udf(), runtime="Python"),
                                              size=[
                                             {'dimension': 'x', 'value': size, 'unit': 'px'},
                                             {'dimension': 'y', 'value': size, 'unit': 'px'}
                                         ], overlap=[])
```

However this results in an error that is also reported in https://github.com/Open-EO/openeo-geopyspark-driver/issues/434

**Comment by JanssenBrm** [comment]
It looks like summarizing your experiments really help with resolving the issue 😄 . After looking at the screenshots I noticed that the resulting band from the UDF is called `var`. Applying the following code did the trick:

```python
phenology = phenology.add_dimension('var', phenology_bands[0], 'bands')
phenology = phenology.rename_labels(dimension='var', target=phenology_bands)
```

**Comment by soxofaan** [comment]
[ :duck: ](https://en.wikipedia.org/wiki/Rubber_duck_debugging)
