### ISSUE TITLE
Make the time steps size configurable in the mogpr method

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/FuseTS#96]
When using the [fusets.mogpr method](https://github.com/Open-EO/FuseTS/blob/e7d82a85e403df29dda88bb6cc33f9c95a6de3c7/src/fusets/mogpr.py#L136), the size of the temporal steps is enforced to 5. This constraint is not explained in the documentation: this gave me erroneous output data when I tried to use the method on data that was composited on 10 days.

Would it be possible to let the user specify the size of temporal steps, or maybe to try to deduce it from the input array coordinates?

Implementing a check that raises an error if temporal coordinates do not match the temporal step size would also help the user to use the function correctly.

@JanssenBrm

**Comment by mlubej** [comment]
@GriffinBabe I am implementing this functionality, but in the past I've only run the local version of the function. Do you perhaps still have an MVP code/notebook for running a small area with the open-eo implementation of mogpr, so I can test it?
